<div style="background: linear-gradient(135deg, #0d47a1 0%, #1976d2 50%, #42a5f5 100%); padding: 26px 30px; border-radius: 16px; color: #ffffff; margin-bottom: 22px; box-shadow: 0 8px 24px rgba(25, 118, 210, 0.25); border: 1px solid rgba(255, 255, 255, 0.15);">
  <div style="display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 14px;">
    <div>
      <span style="background: rgba(255, 255, 255, 0.2); padding: 5px 14px; border-radius: 20px; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 1.2px; display: inline-block; margin-bottom: 10px;">
        Machine Learning Basics
      </span>
      <h1 style="margin: 0; color: #ffffff; font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, Roboto, sans-serif; font-size: 32px; font-weight: 800; letter-spacing: -0.5px;">
        🐼 Pandas Basics for Data Science & ML
      </h1>
      <p style="margin: 10px 0 0 0; color: #e3f2fd; font-size: 15px; max-width: 650px; line-height: 1.6;">
        Master data wrangling, tabular manipulation, feature engineering, and preparation workflows for machine learning models.
      </p>
    </div>
    <div style="display: flex; align-items: center;">
      <a href="https://colab.research.google.com/github/DebarghyaAich/Machine_Learning_Basics/blob/main/pandas.ipynb" target="_blank">
        <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab" style="height: 34px; filter: drop-shadow(0 2px 6px rgba(0,0,0,0.25));" />
      </a>
    </div>
  </div>
  <div style="margin-top: 18px; padding-top: 14px; border-top: 1px solid rgba(255, 255, 255, 0.22); display: flex; gap: 20px; font-size: 12px; color: #bbdefb; flex-wrap: wrap; font-weight: 500;">
    <span>⚡ <b>Kernel:</b> Python 3.12 (ML Basics)</span>
    <span>📊 <b>Topic:</b> Tabular Data & EDA</span>
    <span>📂 <b>Author:</b> Debarghya Aich</span>
  </div>
</div>

In [2]:
import pandas as pd
import numpy as np

print(f"Pandas version : {pd.__version__}")
print(f"NumPy version  : {np.__version__}")

Pandas version : 3.0.6
NumPy version  : 2.5.3

<div style="border-left: 5px solid #1976d2; padding: 10px 18px; background: rgba(25, 118, 210, 0.08); border-radius: 0 10px 10px 0; margin: 24px 0 14px 0;">
  <h2 style="margin: 0; color: #1565c0; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 21px; font-weight: 700; display: flex; align-items: center; gap: 10px;">
    <span>📊</span> 1. Creating Series and DataFrames
  </h2>
</div>

In [10]:
#Creaitng a series
labels= ['a','b','c']
my_list= [10,20,30]
arr= np.array([10,20,30])
dict= {1:10,2:20,3:30}

In [11]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [12]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [13]:
pd.Series(arr,index=labels)

a    10
b    20
c    30
dtype: int64

In [16]:
pd.Series(dict)

1    10
2    20
3    30
dtype: int64

In [19]:
# Creating Dtataframes
data={
    'Name':['John','Anna','Peter','Linda'],
    'Age':[28,34,29,42],
    'City':['New York','Paris','Berlin','London'],
    'Salary':[65000,70000,62000,85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [25]:
data_list =[
    ['John',28,'New York',65000],
    ['Anna',34,'Paris',70000],
    ['Peter',29,'Berlin',62000],
    ['Linda',42,'London',85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

<div style="border-left: 5px solid #1976d2; padding: 10px 18px; background: rgba(25, 118, 210, 0.08); border-radius: 0 10px 10px 0; margin: 24px 0 14px 0;">
  <h2 style="margin: 0; color: #1565c0; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 21px; font-weight: 700; display: flex; align-items: center; gap: 10px;">
    <span>🔍</span> 2. selection & Indexing of Cloumns
  </h2>
</div>

In [27]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [28]:
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [32]:
df2[["Name","Age"]]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

<div style="border-left: 5px solid #1976d2; padding: 10px 18px; background: rgba(25, 118, 210, 0.08); border-radius: 0 10px 10px 0; margin: 24px 0 14px 0;">
  <h2 style="margin: 0; color: #1565c0; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 21px; font-weight: 700; display: flex; align-items: center; gap: 10px;">
    <span>🔍</span> 3. Adding Columns
  </h2>
</div>

In [45]:
df2["Designation"]=["Doctor","Engineer","Doctor","Engineer"]

In [46]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

<div style="border-left: 5px solid #1976d2; padding: 10px 18px; background: rgba(25, 118, 210, 0.08); border-radius: 0 10px 10px 0; margin: 24px 0 14px 0;">
  <h2 style="margin: 0; color: #1565c0; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 21px; font-weight: 700; display: flex; align-items: center; gap: 10px;">
    <span>🔍</span> 4. Removing Columns
  </h2>
</div>

In [48]:
df2.drop("Designation",axis=1,inplace=True)

<div style="border-left: 5px solid #1976d2; padding: 10px 18px; background: rgba(25, 118, 210, 0.08); border-radius: 0 10px 10px 0; margin: 24px 0 14px 0;">
  <h2 style="margin: 0; color: #1565c0; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 21px; font-weight: 700; display: flex; align-items: center; gap: 10px;">
    <span>🔍</span> 5. Selecting Rows
  </h2>
</div>

In [50]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [54]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [55]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

<div style="border-left: 5px solid #1976d2; padding: 10px 18px; background: rgba(25, 118, 210, 0.08); border-radius: 0 10px 10px 0; margin: 24px 0 14px 0;">
  <h2 style="margin: 0; color: #1565c0; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 21px; font-weight: 700; display: flex; align-items: center; gap: 10px;">
    <span>🔍</span> 6. Removing Rows
  </h2>
</div>

In [53]:
df2.drop(3,axis=0)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000

<div style="border-left: 5px solid #1976d2; padding: 10px 18px; background: rgba(25, 118, 210, 0.08); border-radius: 0 10px 10px 0; margin: 24px 0 14px 0;">
  <h2 style="margin: 0; color: #1565c0; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 21px; font-weight: 700; display: flex; align-items: center; gap: 10px;">
    <span>🔍</span> 7. Selecting subsets of rows & Columns
  </h2>
</div>

In [56]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [57]:
df2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [59]:
df2.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

<div style="border-left: 5px solid #1976d2; padding: 10px 18px; background: rgba(25, 118, 210, 0.08); border-radius: 0 10px 10px 0; margin: 24px 0 14px 0;">
  <h2 style="margin: 0; color: #1565c0; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 21px; font-weight: 700; display: flex; align-items: center; gap: 10px;">
    <span>🔍</span> 7. Conditional Selection
  </h2>
</div>

In [64]:
# only those rows whose age is greater than 30
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [67]:
# only those whose age>30 and city = paris 
df2[(df2["Age"]>30) & (df2["City"]=='Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

<div style="border-left: 5px solid #1976d2; padding: 10px 18px; background: rgba(25, 118, 210, 0.08); border-radius: 0 10px 10px 0; margin: 24px 0 14px 0;">
  <h2 style="margin: 0; color: #1565c0; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 21px; font-weight: 700; display: flex; align-items: center; gap: 10px;">
    <span>🔍</span> Finding Missing Data
  </h2>
</div>

In [70]:
data={
    'A':[1,2,np.nan,4,5],
    'B':[np.nan,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}
df=pd.DataFrame(data)
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [71]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [72]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [73]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

<div style="border-left: 5px solid #1976d2; padding: 10px 18px; background: rgba(25, 118, 210, 0.08); border-radius: 0 10px 10px 0; margin: 24px 0 14px 0;">
  <h2 style="margin: 0; color: #1565c0; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 21px; font-weight: 700; display: flex; align-items: center; gap: 10px;">
    <span>🔍</span> Removing Missing Data
  </h2>
</div>

In [74]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [75]:
df.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []