<div style="background: linear-gradient(135deg, #0d47a1 0%, #1976d2 50%, #42a5f5 100%); padding: 26px 30px; border-radius: 16px; color: #ffffff; margin-bottom: 22px; box-shadow: 0 8px 24px rgba(25, 118, 210, 0.25); border: 1px solid rgba(255, 255, 255, 0.15);">
  <div style="display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 14px;">
    <div>
      <span style="background: rgba(255, 255, 255, 0.2); padding: 5px 14px; border-radius: 20px; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 1.2px; display: inline-block; margin-bottom: 10px;">
        Machine Learning Basics
      </span>
      <h1 style="margin: 0; color: #ffffff; font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, Roboto, sans-serif; font-size: 32px; font-weight: 800; letter-spacing: -0.5px;">
        🐼 Pandas Basics for Data Science & ML
      </h1>
      <p style="margin: 10px 0 0 0; color: #e3f2fd; font-size: 15px; max-width: 650px; line-height: 1.6;">
        Master data wrangling, tabular manipulation, feature engineering, and preparation workflows for machine learning models.
      </p>
    </div>
    <div style="display: flex; align-items: center;">
      <a href="https://colab.research.google.com/github/DebarghyaAich/Machine_Learning_Basics/blob/main/pandas.ipynb" target="_blank">
        <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab" style="height: 34px; filter: drop-shadow(0 2px 6px rgba(0,0,0,0.25));" />
      </a>
    </div>
  </div>
  <div style="margin-top: 18px; padding-top: 14px; border-top: 1px solid rgba(255, 255, 255, 0.22); display: flex; gap: 20px; font-size: 12px; color: #bbdefb; flex-wrap: wrap; font-weight: 500;">
    <span>⚡ <b>Kernel:</b> Python 3.12 (ML Basics)</span>
    <span>📊 <b>Topic:</b> Tabular Data & EDA</span>
    <span>📂 <b>Author:</b> Debarghya Aich</span>
  </div>
</div>

In [2]:
import pandas as pd
import numpy as np

print(f"Pandas version : {pd.__version__}")
print(f"NumPy version  : {np.__version__}")

Pandas version : 3.0.6
NumPy version  : 2.5.3

<div style="border-left: 5px solid #1976d2; padding: 10px 18px; background: rgba(25, 118, 210, 0.08); border-radius: 0 10px 10px 0; margin: 26px 0 14px 0;">
  <h2 style="margin: 0; color: #0d47a1; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 21px; font-weight: 700; display: flex; align-items: center; gap: 10px;">
    <span>📊</span> 1. Creating Series and DataFrames
  </h2>
</div>

In [10]:
#Creaitng a series
labels= ['a','b','c']
my_list= [10,20,30]
arr= np.array([10,20,30])
dict= {1:10,2:20,3:30}

In [11]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [12]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [13]:
pd.Series(arr,index=labels)

a    10
b    20
c    30
dtype: int64

In [16]:
pd.Series(dict)

1    10
2    20
3    30
dtype: int64

In [19]:
# Creating Dtataframes
data={
    'Name':['John','Anna','Peter','Linda'],
    'Age':[28,34,29,42],
    'City':['New York','Paris','Berlin','London'],
    'Salary':[65000,70000,62000,85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [25]:
data_list =[
    ['John',28,'New York',65000],
    ['Anna',34,'Paris',70000],
    ['Peter',29,'Berlin',62000],
    ['Linda',42,'London',85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

<div style="border-left: 5px solid #1976d2; padding: 10px 18px; background: rgba(25, 118, 210, 0.08); border-radius: 0 10px 10px 0; margin: 26px 0 14px 0;">
  <h2 style="margin: 0; color: #0d47a1; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 21px; font-weight: 700; display: flex; align-items: center; gap: 10px;">
    <span>🎯</span> 2. Selection & Indexing of Columns
  </h2>
</div>

In [27]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [28]:
df2["Name"]

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [32]:
df2[["Name","Age"]]

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

<div style="border-left: 4px solid #42a5f5; padding: 8px 16px; background: rgba(66, 165, 245, 0.06); border-radius: 0 8px 8px 0; margin: 20px 0 12px 0;">
  <h3 style="margin: 0; color: #1565c0; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 18px; font-weight: 600; display: flex; align-items: center; gap: 8px;">
    <span>➕</span> 3. Adding New Columns
  </h3>
</div>

In [45]:
df2["Designation"]=["Doctor","Engineer","Doctor","Engineer"]

In [46]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000      Doctor
1   Anna   34     Paris   70000    Engineer
2  Peter   29    Berlin   62000      Doctor
3  Linda   42    London   85000    Engineer

<div style="border-left: 4px solid #42a5f5; padding: 8px 16px; background: rgba(66, 165, 245, 0.06); border-radius: 0 8px 8px 0; margin: 20px 0 12px 0;">
  <h3 style="margin: 0; color: #1565c0; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 18px; font-weight: 600; display: flex; align-items: center; gap: 8px;">
    <span>🗑️</span> 4. Removing Columns (df.drop(axis=1))
  </h3>
</div>

In [48]:
df2.drop("Designation",axis=1,inplace=True)

<div style="border-left: 4px solid #42a5f5; padding: 8px 16px; background: rgba(66, 165, 245, 0.06); border-radius: 0 8px 8px 0; margin: 20px 0 12px 0;">
  <h3 style="margin: 0; color: #1565c0; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 18px; font-weight: 600; display: flex; align-items: center; gap: 8px;">
    <span>📌</span> 5. Selecting Rows (.loc & .iloc)
  </h3>
</div>

In [50]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [54]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [55]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

<div style="border-left: 4px solid #42a5f5; padding: 8px 16px; background: rgba(66, 165, 245, 0.06); border-radius: 0 8px 8px 0; margin: 20px 0 12px 0;">
  <h3 style="margin: 0; color: #1565c0; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 18px; font-weight: 600; display: flex; align-items: center; gap: 8px;">
    <span>✂️</span> 6. Removing Rows (df.drop(axis=0))
  </h3>
</div>

In [53]:
df2.drop(3,axis=0)

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000

<div style="border-left: 4px solid #42a5f5; padding: 8px 16px; background: rgba(66, 165, 245, 0.06); border-radius: 0 8px 8px 0; margin: 20px 0 12px 0;">
  <h3 style="margin: 0; color: #1565c0; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 18px; font-weight: 600; display: flex; align-items: center; gap: 8px;">
    <span>🧩</span> 7. Selecting Subsets of Rows & Columns
  </h3>
</div>

In [56]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [57]:
df2.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [59]:
df2.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

<div style="border-left: 5px solid #1976d2; padding: 10px 18px; background: rgba(25, 118, 210, 0.08); border-radius: 0 10px 10px 0; margin: 26px 0 14px 0;">
  <h2 style="margin: 0; color: #0d47a1; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 21px; font-weight: 700; display: flex; align-items: center; gap: 10px;">
    <span>🔍</span> 8. Conditional Selection & Boolean Masking
  </h2>
</div>

In [64]:
# only those rows whose age is greater than 30
df2[df2["Age"]>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [67]:
# only those whose age>30 and city = paris 
df2[(df2["Age"]>30) & (df2["City"]=='Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

<div style="background: linear-gradient(135deg, #0d47a1 0%, #1565c0 50%, #1976d2 100%); padding: 22px 28px; border-radius: 14px; color: #ffffff; margin: 34px 0 20px 0; box-shadow: 0 6px 18px rgba(13, 71, 161, 0.25);">
  <span style="background: rgba(255, 255, 255, 0.2); padding: 4px 12px; border-radius: 20px; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; display: inline-block; margin-bottom: 8px;">
    Data Quality & Cleaning
  </span>
  <h2 style="margin: 0; color: #ffffff; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 23px; font-weight: 800; display: flex; align-items: center; gap: 10px;">
    <span>🧹</span> Module II: Handling Missing Data (.isna, .dropna, .fillna)
  </h2>
    <p style="margin: 8px 0 0 0; color: #e3f2fd; font-size: 14px; line-height: 1.5;">Detect null entries, filter records with threshold constraints, and impute missing values cleanly.</p>
</div>

<div style="border-left: 4px solid #42a5f5; padding: 8px 16px; background: rgba(66, 165, 245, 0.06); border-radius: 0 8px 8px 0; margin: 20px 0 12px 0;">
  <h3 style="margin: 0; color: #1565c0; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 18px; font-weight: 600; display: flex; align-items: center; gap: 8px;">
    <span>🔎</span> 9.1 Detecting Missing Values (.isna() & .isnull())
  </h3>
</div>

In [70]:
data={
    'A':[1,2,np.nan,4,5],
    'B':[np.nan,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5]
}
df=pd.DataFrame(data)
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [71]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [72]:
df.isna().any()

A    True
B    True
C    True
D    True
dtype: bool

In [73]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

<div style="border-left: 4px solid #42a5f5; padding: 8px 16px; background: rgba(66, 165, 245, 0.06); border-radius: 0 8px 8px 0; margin: 20px 0 12px 0;">
  <h3 style="margin: 0; color: #1565c0; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 18px; font-weight: 600; display: flex; align-items: center; gap: 8px;">
    <span>🗑️</span> 9.2 Dropping Missing Records (.dropna(axis, thresh))
  </h3>
</div>

In [74]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

In [75]:
df.dropna()

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [82]:
df.dropna(thresh=3)  #there should be atleast 3 non-null values in a row.

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
4  5.0  5.0  NaN  5.0

<div style="border-left: 4px solid #42a5f5; padding: 8px 16px; background: rgba(66, 165, 245, 0.06); border-radius: 0 8px 8px 0; margin: 20px 0 12px 0;">
  <h3 style="margin: 0; color: #1565c0; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 18px; font-weight: 600; display: flex; align-items: center; gap: 8px;">
    <span>🩹</span> 9.3 Imputing & Filling Missing Values (.fillna())
  </h3>
</div>

In [ ]:
df.fillna(0) # applied on main data when  (inplace=true)

     A    B    C    D
0  1.0  0.0  1.0  1.0
1  2.0  2.0  2.0  0.0
2  0.0  3.0  3.0  0.0
3  4.0  4.0  0.0  0.0
4  5.0  5.0  0.0  5.0

In [85]:
values={'A':10,'B':100,'c':300,'D':200}
df.fillna(value =values)

      A      B    C      D
0   1.0  100.0  1.0    1.0
1   2.0    2.0  2.0  200.0
2  10.0    3.0  3.0  200.0
3   4.0    4.0  NaN  200.0
4   5.0    5.0  NaN    5.0

In [86]:
df.fillna(df.mean())

     A    B    C    D
0  1.0  3.5  1.0  1.0
1  2.0  2.0  2.0  3.0
2  3.0  3.0  3.0  3.0
3  4.0  4.0  2.0  3.0
4  5.0  5.0  2.0  5.0

<div style="background: linear-gradient(135deg, #0d47a1 0%, #1565c0 50%, #1976d2 100%); padding: 22px 28px; border-radius: 14px; color: #ffffff; margin: 34px 0 20px 0; box-shadow: 0 6px 18px rgba(13, 71, 161, 0.25);">
  <span style="background: rgba(255, 255, 255, 0.2); padding: 4px 12px; border-radius: 20px; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; display: inline-block; margin-bottom: 8px;">
    Relational Data Operations
  </span>
  <h2 style="margin: 0; color: #ffffff; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 23px; font-weight: 800; display: flex; align-items: center; gap: 10px;">
    <span>🔗</span> Module III: Combining Data (Merge, Concat & Join)
  </h2>
    <p style="margin: 8px 0 0 0; color: #e3f2fd; font-size: 14px; line-height: 1.5;">Combine multi-table datasets using relational keys, index alignment, and axis-based stacking.</p>
</div>

In [88]:
# DataFrame 1: Employee Basic Info
df1 = pd.DataFrame({
    'emp_id': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40]
})
df1

   emp_id     Name  Age
0     101    Alice   25
1     102      Bob   30
2     103  Charlie   35
3     104    David   40

In [89]:
df2 = pd.DataFrame({
    'emp_id': [103, 104, 105, 106],
    'Department': ['IT', 'HR', 'Finance', 'Marketing'],
    'Salary': [75000, 62000, 80000, 58000]
})
df2

   emp_id Department  Salary
0     103         IT   75000
1     104         HR   62000
2     105    Finance   80000
3     106  Marketing   58000

<div style="border-left: 4px solid #42a5f5; padding: 8px 16px; background: rgba(66, 165, 245, 0.06); border-radius: 0 8px 8px 0; margin: 20px 0 12px 0;">
  <h3 style="margin: 0; color: #1565c0; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 18px; font-weight: 600; display: flex; align-items: center; gap: 8px;">
    <span>🔀</span> 10.1 Relational Merging on Common Columns (pd.merge)
  </h3>
</div>

In [91]:
pd.merge(df1,df2,on="emp_id",how="inner")

   emp_id     Name  Age Department  Salary
0     103  Charlie   35         IT   75000
1     104    David   40         HR   62000

In [98]:
pd.merge(df1,df2,on="emp_id",how="outer")

   emp_id     Name   Age Department   Salary
0     101    Alice  25.0        NaN      NaN
1     102      Bob  30.0        NaN      NaN
2     103  Charlie  35.0         IT  75000.0
3     104    David  40.0         HR  62000.0
4     105      NaN   NaN    Finance  80000.0
5     106      NaN   NaN  Marketing  58000.0

In [99]:
pd.merge(df1,df2,on="emp_id",how="left")

   emp_id     Name  Age Department   Salary
0     101    Alice   25        NaN      NaN
1     102      Bob   30        NaN      NaN
2     103  Charlie   35         IT  75000.0
3     104    David   40         HR  62000.0

In [105]:
pd.merge(df1,df2,on="emp_id",how="right")

   emp_id     Name   Age Department  Salary
0     103  Charlie  35.0         IT   75000
1     104    David  40.0         HR   62000
2     105      NaN   NaN    Finance   80000
3     106      NaN   NaN  Marketing   58000

<div style="border-left: 4px solid #42a5f5; padding: 8px 16px; background: rgba(66, 165, 245, 0.06); border-radius: 0 8px 8px 0; margin: 20px 0 12px 0;">
  <h3 style="margin: 0; color: #1565c0; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 18px; font-weight: 600; display: flex; align-items: center; gap: 8px;">
    <span>🧱</span> 10.2 Concatenating DataFrames (pd.concat along axis=0 / axis=1)
  </h3>
</div>

In [ ]:
pd.concat([df1,df2])  # colummn wise

   emp_id     Name   Age Department   Salary
0     101    Alice  25.0        NaN      NaN
1     102      Bob  30.0        NaN      NaN
2     103  Charlie  35.0        NaN      NaN
3     104    David  40.0        NaN      NaN
0     103      NaN   NaN         IT  75000.0
1     104      NaN   NaN         HR  62000.0
2     105      NaN   NaN    Finance  80000.0
3     106      NaN   NaN  Marketing  58000.0

In [ ]:
pd.concat([df1,df2],axis=1)   # row wise

   emp_id     Name  Age  emp_id Department  Salary
0     101    Alice   25     103         IT   75000
1     102      Bob   30     104         HR   62000
2     103  Charlie   35     105    Finance   80000
3     104    David   40     106  Marketing   58000

<div style="border-left: 4px solid #42a5f5; padding: 8px 16px; background: rgba(66, 165, 245, 0.06); border-radius: 0 8px 8px 0; margin: 20px 0 12px 0;">
  <h3 style="margin: 0; color: #1565c0; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 18px; font-weight: 600; display: flex; align-items: center; gap: 8px;">
    <span>🧩</span> 10.3 Index-Based Joining (.join())
  </h3>
</div>

In [115]:
df1_indexed = df1.set_index('emp_id')
df2_indexed = df2.set_index('emp_id')
df1_indexed.join(df2_indexed,how='inner')

           Name  Age Department  Salary
emp_id
103     Charlie   35         IT   75000
104       David   40         HR   62000

In [118]:
df1_indexed.join(df2_indexed,how='outer')

           Name   Age Department   Salary
emp_id
101       Alice  25.0        NaN      NaN
102         Bob  30.0        NaN      NaN
103     Charlie  35.0         IT  75000.0
104       David  40.0         HR  62000.0
105         NaN   NaN    Finance  80000.0
106         NaN   NaN  Marketing  58000.0

In [119]:
df1_indexed.join(df2_indexed)

           Name  Age Department   Salary
emp_id
101       Alice   25        NaN      NaN
102         Bob   30        NaN      NaN
103     Charlie   35         IT  75000.0
104       David   40         HR  62000.0

In [120]:
df2_indexed.join(df1_indexed)

       Department  Salary     Name   Age
emp_id
103            IT   75000  Charlie  35.0
104            HR   62000    David  40.0
105       Finance   80000      NaN   NaN
106     Marketing   58000      NaN   NaN

<div style="background: linear-gradient(135deg, #0d47a1 0%, #1565c0 50%, #1976d2 100%); padding: 22px 28px; border-radius: 14px; color: #ffffff; margin: 34px 0 20px 0; box-shadow: 0 6px 18px rgba(13, 71, 161, 0.25);">
  <span style="background: rgba(255, 255, 255, 0.2); padding: 4px 12px; border-radius: 20px; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; display: inline-block; margin-bottom: 8px;">
    Relational Data Operations
  </span>
  <h2 style="margin: 0; color: #ffffff; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 23px; font-weight: 800; display: flex; align-items: center; gap: 10px;">
    <span>🔗</span> Module IV: GroupBy and Aggregation
  </h2>
    <p style="margin: 8px 0 0 0; color: #e3f2fd; font-size: 14px; line-height: 1.5;">Combine multi-table datasets using relational keys, index alignment, and axis-based stacking.</p>
</div>

In [122]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

Groupby

In [128]:
df.groupby('Category')['Sales'].sum()

Category
A    570
B    930
Name: Sales, dtype: int64

In [131]:
df.groupby(['Category','Store'])['Sales'].mean()

Category  Store
A         S1       110.0
          S2       175.0
B         S1       250.0
          S2       215.0
Name: Sales, dtype: float64

Aggregation

In [133]:
df['Sales'].agg(['mean','median','min','max','sum','count','std'])

mean       187.500000
median     190.000000
min        100.000000
max        300.000000
sum       1500.000000
count        8.000000
std         66.062741
Name: Sales, dtype: float64

<div style="background: linear-gradient(135deg, #0d47a1 0%, #1565c0 50%, #1976d2 100%); padding: 22px 28px; border-radius: 14px; color: #ffffff; margin: 34px 0 20px 0; box-shadow: 0 6px 18px rgba(13, 71, 161, 0.25);">
  <span style="background: rgba(255, 255, 255, 0.2); padding: 4px 12px; border-radius: 20px; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; display: inline-block; margin-bottom: 8px;">
    Relational Data Operations
  </span>
  <h2 style="margin: 0; color: #ffffff; font-family: 'Segoe UI', -apple-system, sans-serif; font-size: 23px; font-weight: 800; display: flex; align-items: center; gap: 10px;">
    <span>🔗</span> Module V: Pivot Table
  </h2>
    <p style="margin: 8px 0 0 0; color: #e3f2fd; font-size: 14px; line-height: 1.5;">Combine multi-table datasets using relational keys, index alignment, and axis-based stacking.</p>
</div>

In [134]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    155     34   John
1  2023-01-02       B   West    830     86   Mary
2  2023-01-03       C  North    461     37    Bob
3  2023-01-04       D  South    159     68  Alice
4  2023-01-05       A   East    612     40   John
5  2023-01-06       B   West    390     62   Mary
6  2023-01-07       C  North    936     72    Bob
7  2023-01-08       D  South    131     78  Alice
8  2023-01-09       A   East    527     10   John
9  2023-01-10       B   West    186     24   Mary
10 2023-01-11       C  North    102     26    Bob
11 2023-01-12       D  South    147     66  Alice
12 2023-01-13       A   East    583     54   John
13 2023-01-14       B   West    962     55   Mary
14 2023-01-15       C  North    227     67    Bob
15 2023-01-16       D  South    468     42  Alice
16 2023-01-17       A   East    987     88   John
17 2023-01-18       B   West    939     24   Mary
18 2023-01-19       C  North    595     98    Bob
19 2023-01-20       D  South    902     46  Alice

pivot tables

In [139]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='median')

Product      A      B      C      D
Region
East     583.0    NaN    NaN    NaN
North      NaN    NaN  461.0    NaN
South      NaN    NaN    NaN  159.0
West       NaN  830.0    NaN    NaN

In [140]:
pd.pivot_table(df,values=['Sales','Units'],index='Region',columns='Product',aggfunc='mean')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     572.8    NaN    NaN    NaN  45.2   NaN   NaN   NaN
North      NaN    NaN  464.2    NaN   NaN   NaN  60.0   NaN
South      NaN    NaN    NaN  361.4   NaN   NaN   NaN  60.0
West       NaN  661.4    NaN    NaN   NaN  50.2   NaN   NaN

cross tabs